// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-processor-sdk/pprocutils (interfaces: HTTPService)
//
// Generated by this command:
//
//	mockgen -typed -destination=mock/http.go -package=mock -mock_names=HTTPService=HTTPService . HTTPService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pprocutils "github.com/conduitio/conduit-processor-sdk/pprocutils"
	gomock "go.uber.org/mock/gomock"
)

// HTTPService is a mock of HTTPService interface.
type HTTPService struct {
	ctrl     *gomock.Controller
	recorder *HTTPServiceMockRecorder
	isgomock struct{}
}

// HTTPServiceMockRecorder is the mock recorder for HTTPService.
type HTTPServiceMockRecorder struct {
	mock *HTTPService
}

// NewHTTPService creates a new mock instance.
func NewHTTPService(ctrl *gomock.Controller) *HTTPService {
	mock := &HTTPService{ctrl: ctrl}
	mock.recorder = &HTTPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *HTTPService) EXPECT() *HTTPServiceMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *HTTPService) Do(ctx context.Context, req pprocutils.HTTPRequest) (pprocutils.HTTPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(pprocutils.HTTPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *HTTPServiceMockRecorder) Do(ctx, req any) *HTTPServiceDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*HTTPService)(nil).Do), ctx, req)
	return &HTTPServiceDoCall{Call: call}
}

// HTTPServiceDoCall wrap *gomock.Call
type HTTPServiceDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *HTTPServiceDoCall) Return(arg0 pprocutils.HTTPResponse, arg1 error) *HTTPServiceDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *HTTPServiceDoCall) Do(f func(context.Context, pprocutils.HTTPRequest) (pprocutils.HTTPResponse, error)) *HTTPServiceDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *HTTPServiceDoCall) DoAndReturn(f func(context.Context, pprocutils.HTTPRequest) (pprocutils.HTTPResponse, error)) *HTTPServiceDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
