// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: processor/v1/processor.proto

package processorv1

import (
	v1 "github.com/conduitio/conduit-commons/proto/config/v1"
	v11 "github.com/conduitio/conduit-commons/proto/opencdc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*CommandRequest_Specify
	//	*CommandRequest_Configure
	//	*CommandRequest_Open
	//	*CommandRequest_Process
	//	*CommandRequest_Teardown
	Request isCommandRequest_Request `protobuf_oneof:"request"`
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{0}
}

func (m *CommandRequest) GetRequest() isCommandRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *CommandRequest) GetSpecify() *Specify_Request {
	if x, ok := x.GetRequest().(*CommandRequest_Specify); ok {
		return x.Specify
	}
	return nil
}

func (x *CommandRequest) GetConfigure() *Configure_Request {
	if x, ok := x.GetRequest().(*CommandRequest_Configure); ok {
		return x.Configure
	}
	return nil
}

func (x *CommandRequest) GetOpen() *Open_Request {
	if x, ok := x.GetRequest().(*CommandRequest_Open); ok {
		return x.Open
	}
	return nil
}

func (x *CommandRequest) GetProcess() *Process_Request {
	if x, ok := x.GetRequest().(*CommandRequest_Process); ok {
		return x.Process
	}
	return nil
}

func (x *CommandRequest) GetTeardown() *Teardown_Request {
	if x, ok := x.GetRequest().(*CommandRequest_Teardown); ok {
		return x.Teardown
	}
	return nil
}

type isCommandRequest_Request interface {
	isCommandRequest_Request()
}

type CommandRequest_Specify struct {
	Specify *Specify_Request `protobuf:"bytes,1,opt,name=specify,proto3,oneof"`
}

type CommandRequest_Configure struct {
	Configure *Configure_Request `protobuf:"bytes,2,opt,name=configure,proto3,oneof"`
}

type CommandRequest_Open struct {
	Open *Open_Request `protobuf:"bytes,3,opt,name=open,proto3,oneof"`
}

type CommandRequest_Process struct {
	Process *Process_Request `protobuf:"bytes,4,opt,name=process,proto3,oneof"`
}

type CommandRequest_Teardown struct {
	Teardown *Teardown_Request `protobuf:"bytes,5,opt,name=teardown,proto3,oneof"`
}

func (*CommandRequest_Specify) isCommandRequest_Request() {}

func (*CommandRequest_Configure) isCommandRequest_Request() {}

func (*CommandRequest_Open) isCommandRequest_Request() {}

func (*CommandRequest_Process) isCommandRequest_Request() {}

func (*CommandRequest_Teardown) isCommandRequest_Request() {}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*CommandResponse_Error
	//	*CommandResponse_Specify
	//	*CommandResponse_Configure
	//	*CommandResponse_Open
	//	*CommandResponse_Process
	//	*CommandResponse_Teardown
	Response isCommandResponse_Response `protobuf_oneof:"response"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{1}
}

func (m *CommandResponse) GetResponse() isCommandResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CommandResponse) GetError() *Error {
	if x, ok := x.GetResponse().(*CommandResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *CommandResponse) GetSpecify() *Specify_Response {
	if x, ok := x.GetResponse().(*CommandResponse_Specify); ok {
		return x.Specify
	}
	return nil
}

func (x *CommandResponse) GetConfigure() *Configure_Response {
	if x, ok := x.GetResponse().(*CommandResponse_Configure); ok {
		return x.Configure
	}
	return nil
}

func (x *CommandResponse) GetOpen() *Open_Response {
	if x, ok := x.GetResponse().(*CommandResponse_Open); ok {
		return x.Open
	}
	return nil
}

func (x *CommandResponse) GetProcess() *Process_Response {
	if x, ok := x.GetResponse().(*CommandResponse_Process); ok {
		return x.Process
	}
	return nil
}

func (x *CommandResponse) GetTeardown() *Teardown_Response {
	if x, ok := x.GetResponse().(*CommandResponse_Teardown); ok {
		return x.Teardown
	}
	return nil
}

type isCommandResponse_Response interface {
	isCommandResponse_Response()
}

type CommandResponse_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type CommandResponse_Specify struct {
	Specify *Specify_Response `protobuf:"bytes,2,opt,name=specify,proto3,oneof"`
}

type CommandResponse_Configure struct {
	Configure *Configure_Response `protobuf:"bytes,3,opt,name=configure,proto3,oneof"`
}

type CommandResponse_Open struct {
	Open *Open_Response `protobuf:"bytes,4,opt,name=open,proto3,oneof"`
}

type CommandResponse_Process struct {
	Process *Process_Response `protobuf:"bytes,5,opt,name=process,proto3,oneof"`
}

type CommandResponse_Teardown struct {
	Teardown *Teardown_Response `protobuf:"bytes,6,opt,name=teardown,proto3,oneof"`
}

func (*CommandResponse_Error) isCommandResponse_Response() {}

func (*CommandResponse_Specify) isCommandResponse_Response() {}

func (*CommandResponse_Configure) isCommandResponse_Response() {}

func (*CommandResponse_Open) isCommandResponse_Response() {}

func (*CommandResponse_Process) isCommandResponse_Response() {}

func (*CommandResponse_Teardown) isCommandResponse_Response() {}

type Specify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specify) Reset() {
	*x = Specify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify) ProtoMessage() {}

func (x *Specify) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify.ProtoReflect.Descriptor instead.
func (*Specify) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2}
}

type Configure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Configure) Reset() {
	*x = Configure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure) ProtoMessage() {}

func (x *Configure) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure.ProtoReflect.Descriptor instead.
func (*Configure) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3}
}

type Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open) Reset() {
	*x = Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4}
}

type Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Process) Reset() {
	*x = Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5}
}

type Teardown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Teardown) Reset() {
	*x = Teardown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown) ProtoMessage() {}

func (x *Teardown) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown.ProtoReflect.Descriptor instead.
func (*Teardown) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Specify_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specify_Request) Reset() {
	*x = Specify_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Request) ProtoMessage() {}

func (x *Specify_Request) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Request.ProtoReflect.Descriptor instead.
func (*Specify_Request) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 0}
}

type Specify_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name is the name of the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Summary is a brief description of the plugin and what it does,
	// ideally not longer than one sentence.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Description is a longer form field, appropriate for README-like
	// text that the author can provide for documentation about the
	// usage of the plugin.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Version string. Should follow semantic versioning and use the "v"
	// prefix (e.g. v1.23.4).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Author declares the entity that created or maintains this plugin.
	Author string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	// A map that describes parameters available for configuring the
	// processor plugin.
	Parameters map[string]*v1.Parameter `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Specify_Response) Reset() {
	*x = Specify_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Response) ProtoMessage() {}

func (x *Specify_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Response.ProtoReflect.Descriptor instead.
func (*Specify_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Specify_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specify_Response) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Specify_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specify_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Specify_Response) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Specify_Response) GetParameters() map[string]*v1.Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Configure_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Configure_Request) Reset() {
	*x = Configure_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure_Request) ProtoMessage() {}

func (x *Configure_Request) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure_Request.ProtoReflect.Descriptor instead.
func (*Configure_Request) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Configure_Request) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Configure_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Configure_Response) Reset() {
	*x = Configure_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure_Response) ProtoMessage() {}

func (x *Configure_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure_Response.ProtoReflect.Descriptor instead.
func (*Configure_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3, 1}
}

type Open_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open_Request) Reset() {
	*x = Open_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open_Request) ProtoMessage() {}

func (x *Open_Request) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open_Request.ProtoReflect.Descriptor instead.
func (*Open_Request) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4, 0}
}

type Open_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open_Response) Reset() {
	*x = Open_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open_Response) ProtoMessage() {}

func (x *Open_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open_Response.ProtoReflect.Descriptor instead.
func (*Open_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4, 1}
}

type Process_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*v11.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Process_Request) Reset() {
	*x = Process_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Request) ProtoMessage() {}

func (x *Process_Request) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Request.ProtoReflect.Descriptor instead.
func (*Process_Request) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Process_Request) GetRecords() []*v11.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Process_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Process_ProcessedRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Process_Response) Reset() {
	*x = Process_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Response) ProtoMessage() {}

func (x *Process_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Response.ProtoReflect.Descriptor instead.
func (*Process_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Process_Response) GetRecords() []*Process_ProcessedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type Process_ProcessedRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Record:
	//
	//	*Process_ProcessedRecord_SingleRecord
	//	*Process_ProcessedRecord_FilterRecord
	//	*Process_ProcessedRecord_ErrorRecord
	//	*Process_ProcessedRecord_MultiRecord
	Record isProcess_ProcessedRecord_Record `protobuf_oneof:"record"`
}

func (x *Process_ProcessedRecord) Reset() {
	*x = Process_ProcessedRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_ProcessedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_ProcessedRecord) ProtoMessage() {}

func (x *Process_ProcessedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_ProcessedRecord.ProtoReflect.Descriptor instead.
func (*Process_ProcessedRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 2}
}

func (m *Process_ProcessedRecord) GetRecord() isProcess_ProcessedRecord_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *Process_ProcessedRecord) GetSingleRecord() *v11.Record {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_SingleRecord); ok {
		return x.SingleRecord
	}
	return nil
}

func (x *Process_ProcessedRecord) GetFilterRecord() *Process_FilterRecord {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_FilterRecord); ok {
		return x.FilterRecord
	}
	return nil
}

func (x *Process_ProcessedRecord) GetErrorRecord() *Process_ErrorRecord {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_ErrorRecord); ok {
		return x.ErrorRecord
	}
	return nil
}

func (x *Process_ProcessedRecord) GetMultiRecord() *Process_MultiRecord {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_MultiRecord); ok {
		return x.MultiRecord
	}
	return nil
}

type isProcess_ProcessedRecord_Record interface {
	isProcess_ProcessedRecord_Record()
}

type Process_ProcessedRecord_SingleRecord struct {
	SingleRecord *v11.Record `protobuf:"bytes,1,opt,name=single_record,json=singleRecord,proto3,oneof"`
}

type Process_ProcessedRecord_FilterRecord struct {
	FilterRecord *Process_FilterRecord `protobuf:"bytes,2,opt,name=filter_record,json=filterRecord,proto3,oneof"`
}

type Process_ProcessedRecord_ErrorRecord struct {
	ErrorRecord *Process_ErrorRecord `protobuf:"bytes,3,opt,name=error_record,json=errorRecord,proto3,oneof"`
}

type Process_ProcessedRecord_MultiRecord struct {
	MultiRecord *Process_MultiRecord `protobuf:"bytes,4,opt,name=multi_record,json=multiRecord,proto3,oneof"`
}

func (*Process_ProcessedRecord_SingleRecord) isProcess_ProcessedRecord_Record() {}

func (*Process_ProcessedRecord_FilterRecord) isProcess_ProcessedRecord_Record() {}

func (*Process_ProcessedRecord_ErrorRecord) isProcess_ProcessedRecord_Record() {}

func (*Process_ProcessedRecord_MultiRecord) isProcess_ProcessedRecord_Record() {}

type Process_FilterRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Process_FilterRecord) Reset() {
	*x = Process_FilterRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_FilterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_FilterRecord) ProtoMessage() {}

func (x *Process_FilterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_FilterRecord.ProtoReflect.Descriptor instead.
func (*Process_FilterRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 3}
}

type Process_ErrorRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Process_ErrorRecord) Reset() {
	*x = Process_ErrorRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_ErrorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_ErrorRecord) ProtoMessage() {}

func (x *Process_ErrorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_ErrorRecord.ProtoReflect.Descriptor instead.
func (*Process_ErrorRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 4}
}

func (x *Process_ErrorRecord) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Process_MultiRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*v11.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Process_MultiRecord) Reset() {
	*x = Process_MultiRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_MultiRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_MultiRecord) ProtoMessage() {}

func (x *Process_MultiRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_MultiRecord.ProtoReflect.Descriptor instead.
func (*Process_MultiRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 5}
}

func (x *Process_MultiRecord) GetRecords() []*v11.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Teardown_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Teardown_Request) Reset() {
	*x = Teardown_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown_Request) ProtoMessage() {}

func (x *Teardown_Request) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown_Request.ProtoReflect.Descriptor instead.
func (*Teardown_Request) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6, 0}
}

type Teardown_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Teardown_Response) Reset() {
	*x = Teardown_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown_Response) ProtoMessage() {}

func (x *Teardown_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown_Response.ProtoReflect.Descriptor instead.
func (*Teardown_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6, 1}
}

var File_processor_v1_processor_proto protoreflect.FileDescriptor

var file_processor_v1_processor_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63,
	0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc2, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x12,
	0x3f, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x12, 0x30, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x70,
	0x65, 0x6e, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3c, 0x0a,
	0x08, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x08, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xf6, 0x02, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x79, 0x12, 0x40, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x74, 0x65, 0x61, 0x72, 0x64,
	0x6f, 0x77, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xc8, 0x02, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x1a, 0x09, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xb1, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x53, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb3, 0x01, 0x0a, 0x09, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x99, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1d, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xca, 0x04, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x37, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x1a, 0xb1, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x39, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x0c, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x49, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x46, 0x0a, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x46, 0x0a, 0x0c, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0b,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x38, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a,
	0x3b, 0x0a, 0x0b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x2c,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x21, 0x0a, 0x08,
	0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0xbe, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x49, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69,
	0x74, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02,
	0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_processor_v1_processor_proto_rawDescOnce sync.Once
	file_processor_v1_processor_proto_rawDescData = file_processor_v1_processor_proto_rawDesc
)

func file_processor_v1_processor_proto_rawDescGZIP() []byte {
	file_processor_v1_processor_proto_rawDescOnce.Do(func() {
		file_processor_v1_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_processor_v1_processor_proto_rawDescData)
	})
	return file_processor_v1_processor_proto_rawDescData
}

var file_processor_v1_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_processor_v1_processor_proto_goTypes = []interface{}{
	(*CommandRequest)(nil),          // 0: processor.v1.CommandRequest
	(*CommandResponse)(nil),         // 1: processor.v1.CommandResponse
	(*Specify)(nil),                 // 2: processor.v1.Specify
	(*Configure)(nil),               // 3: processor.v1.Configure
	(*Open)(nil),                    // 4: processor.v1.Open
	(*Process)(nil),                 // 5: processor.v1.Process
	(*Teardown)(nil),                // 6: processor.v1.Teardown
	(*Error)(nil),                   // 7: processor.v1.Error
	(*Specify_Request)(nil),         // 8: processor.v1.Specify.Request
	(*Specify_Response)(nil),        // 9: processor.v1.Specify.Response
	nil,                             // 10: processor.v1.Specify.Response.ParametersEntry
	(*Configure_Request)(nil),       // 11: processor.v1.Configure.Request
	(*Configure_Response)(nil),      // 12: processor.v1.Configure.Response
	nil,                             // 13: processor.v1.Configure.Request.ParametersEntry
	(*Open_Request)(nil),            // 14: processor.v1.Open.Request
	(*Open_Response)(nil),           // 15: processor.v1.Open.Response
	(*Process_Request)(nil),         // 16: processor.v1.Process.Request
	(*Process_Response)(nil),        // 17: processor.v1.Process.Response
	(*Process_ProcessedRecord)(nil), // 18: processor.v1.Process.ProcessedRecord
	(*Process_FilterRecord)(nil),    // 19: processor.v1.Process.FilterRecord
	(*Process_ErrorRecord)(nil),     // 20: processor.v1.Process.ErrorRecord
	(*Process_MultiRecord)(nil),     // 21: processor.v1.Process.MultiRecord
	(*Teardown_Request)(nil),        // 22: processor.v1.Teardown.Request
	(*Teardown_Response)(nil),       // 23: processor.v1.Teardown.Response
	(*v1.Parameter)(nil),            // 24: config.v1.Parameter
	(*v11.Record)(nil),              // 25: opencdc.v1.Record
}
var file_processor_v1_processor_proto_depIdxs = []int32{
	8,  // 0: processor.v1.CommandRequest.specify:type_name -> processor.v1.Specify.Request
	11, // 1: processor.v1.CommandRequest.configure:type_name -> processor.v1.Configure.Request
	14, // 2: processor.v1.CommandRequest.open:type_name -> processor.v1.Open.Request
	16, // 3: processor.v1.CommandRequest.process:type_name -> processor.v1.Process.Request
	22, // 4: processor.v1.CommandRequest.teardown:type_name -> processor.v1.Teardown.Request
	7,  // 5: processor.v1.CommandResponse.error:type_name -> processor.v1.Error
	9,  // 6: processor.v1.CommandResponse.specify:type_name -> processor.v1.Specify.Response
	12, // 7: processor.v1.CommandResponse.configure:type_name -> processor.v1.Configure.Response
	15, // 8: processor.v1.CommandResponse.open:type_name -> processor.v1.Open.Response
	17, // 9: processor.v1.CommandResponse.process:type_name -> processor.v1.Process.Response
	23, // 10: processor.v1.CommandResponse.teardown:type_name -> processor.v1.Teardown.Response
	10, // 11: processor.v1.Specify.Response.parameters:type_name -> processor.v1.Specify.Response.ParametersEntry
	24, // 12: processor.v1.Specify.Response.ParametersEntry.value:type_name -> config.v1.Parameter
	13, // 13: processor.v1.Configure.Request.parameters:type_name -> processor.v1.Configure.Request.ParametersEntry
	25, // 14: processor.v1.Process.Request.records:type_name -> opencdc.v1.Record
	18, // 15: processor.v1.Process.Response.records:type_name -> processor.v1.Process.ProcessedRecord
	25, // 16: processor.v1.Process.ProcessedRecord.single_record:type_name -> opencdc.v1.Record
	19, // 17: processor.v1.Process.ProcessedRecord.filter_record:type_name -> processor.v1.Process.FilterRecord
	20, // 18: processor.v1.Process.ProcessedRecord.error_record:type_name -> processor.v1.Process.ErrorRecord
	21, // 19: processor.v1.Process.ProcessedRecord.multi_record:type_name -> processor.v1.Process.MultiRecord
	7,  // 20: processor.v1.Process.ErrorRecord.error:type_name -> processor.v1.Error
	25, // 21: processor.v1.Process.MultiRecord.records:type_name -> opencdc.v1.Record
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_processor_v1_processor_proto_init() }
func file_processor_v1_processor_proto_init() {
	if File_processor_v1_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_processor_v1_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_ProcessedRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_FilterRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_ErrorRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_MultiRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_processor_v1_processor_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CommandRequest_Specify)(nil),
		(*CommandRequest_Configure)(nil),
		(*CommandRequest_Open)(nil),
		(*CommandRequest_Process)(nil),
		(*CommandRequest_Teardown)(nil),
	}
	file_processor_v1_processor_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandResponse_Error)(nil),
		(*CommandResponse_Specify)(nil),
		(*CommandResponse_Configure)(nil),
		(*CommandResponse_Open)(nil),
		(*CommandResponse_Process)(nil),
		(*CommandResponse_Teardown)(nil),
	}
	file_processor_v1_processor_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*Process_ProcessedRecord_SingleRecord)(nil),
		(*Process_ProcessedRecord_FilterRecord)(nil),
		(*Process_ProcessedRecord_ErrorRecord)(nil),
		(*Process_ProcessedRecord_MultiRecord)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processor_v1_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_processor_v1_processor_proto_goTypes,
		DependencyIndexes: file_processor_v1_processor_proto_depIdxs,
		MessageInfos:      file_processor_v1_processor_proto_msgTypes,
	}.Build()
	File_processor_v1_processor_proto = out.File
	file_processor_v1_processor_proto_rawDesc = nil
	file_processor_v1_processor_proto_goTypes = nil
	file_processor_v1_processor_proto_depIdxs = nil
}
