// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: processor/v1/processor.proto

package processorv1

import (
	v1 "github.com/conduitio/conduit-commons/proto/opencdc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type shows the parameter type.
type Specify_Parameter_Type int32

const (
	Specify_Parameter_TYPE_UNSPECIFIED Specify_Parameter_Type = 0
	// Parameter is a string.
	Specify_Parameter_TYPE_STRING Specify_Parameter_Type = 1
	// Parameter is an integer.
	Specify_Parameter_TYPE_INT Specify_Parameter_Type = 2
	// Parameter is a float.
	Specify_Parameter_TYPE_FLOAT Specify_Parameter_Type = 3
	// Parameter is a boolean.
	Specify_Parameter_TYPE_BOOL Specify_Parameter_Type = 4
	// Parameter is a file.
	Specify_Parameter_TYPE_FILE Specify_Parameter_Type = 5
	// Parameter is a duration.
	Specify_Parameter_TYPE_DURATION Specify_Parameter_Type = 6
)

// Enum value maps for Specify_Parameter_Type.
var (
	Specify_Parameter_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_STRING",
		2: "TYPE_INT",
		3: "TYPE_FLOAT",
		4: "TYPE_BOOL",
		5: "TYPE_FILE",
		6: "TYPE_DURATION",
	}
	Specify_Parameter_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_STRING":      1,
		"TYPE_INT":         2,
		"TYPE_FLOAT":       3,
		"TYPE_BOOL":        4,
		"TYPE_FILE":        5,
		"TYPE_DURATION":    6,
	}
)

func (x Specify_Parameter_Type) Enum() *Specify_Parameter_Type {
	p := new(Specify_Parameter_Type)
	*p = x
	return p
}

func (x Specify_Parameter_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Specify_Parameter_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_v1_processor_proto_enumTypes[0].Descriptor()
}

func (Specify_Parameter_Type) Type() protoreflect.EnumType {
	return &file_processor_v1_processor_proto_enumTypes[0]
}

func (x Specify_Parameter_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Specify_Parameter_Type.Descriptor instead.
func (Specify_Parameter_Type) EnumDescriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 2, 0}
}

type Specify_Parameter_Validation_Type int32

const (
	Specify_Parameter_Validation_TYPE_UNSPECIFIED Specify_Parameter_Validation_Type = 0
	// Parameter must be present.
	Specify_Parameter_Validation_TYPE_REQUIRED Specify_Parameter_Validation_Type = 1
	// Parameter must be greater than {value}.
	Specify_Parameter_Validation_TYPE_GREATER_THAN Specify_Parameter_Validation_Type = 2
	// Parameter must be less than {value}.
	Specify_Parameter_Validation_TYPE_LESS_THAN Specify_Parameter_Validation_Type = 3
	// Parameter must be included in the comma separated list {value}.
	Specify_Parameter_Validation_TYPE_INCLUSION Specify_Parameter_Validation_Type = 4
	// Parameter must not be included in the comma separated list {value}.
	Specify_Parameter_Validation_TYPE_EXCLUSION Specify_Parameter_Validation_Type = 5
	// Parameter must match the regex {value}.
	Specify_Parameter_Validation_TYPE_REGEX Specify_Parameter_Validation_Type = 6
)

// Enum value maps for Specify_Parameter_Validation_Type.
var (
	Specify_Parameter_Validation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_REQUIRED",
		2: "TYPE_GREATER_THAN",
		3: "TYPE_LESS_THAN",
		4: "TYPE_INCLUSION",
		5: "TYPE_EXCLUSION",
		6: "TYPE_REGEX",
	}
	Specify_Parameter_Validation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":  0,
		"TYPE_REQUIRED":     1,
		"TYPE_GREATER_THAN": 2,
		"TYPE_LESS_THAN":    3,
		"TYPE_INCLUSION":    4,
		"TYPE_EXCLUSION":    5,
		"TYPE_REGEX":        6,
	}
)

func (x Specify_Parameter_Validation_Type) Enum() *Specify_Parameter_Validation_Type {
	p := new(Specify_Parameter_Validation_Type)
	*p = x
	return p
}

func (x Specify_Parameter_Validation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Specify_Parameter_Validation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_v1_processor_proto_enumTypes[1].Descriptor()
}

func (Specify_Parameter_Validation_Type) Type() protoreflect.EnumType {
	return &file_processor_v1_processor_proto_enumTypes[1]
}

func (x Specify_Parameter_Validation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Specify_Parameter_Validation_Type.Descriptor instead.
func (Specify_Parameter_Validation_Type) EnumDescriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 2, 0, 0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*Command_SpecifyCmd
	//	*Command_ConfigureCmd
	//	*Command_OpenCmd
	//	*Command_ProcessCmd
	//	*Command_TeardownCmd
	Command isCommand_Command `protobuf_oneof:"command"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *Command) GetSpecifyCmd() *Specify_Command {
	if x, ok := x.GetCommand().(*Command_SpecifyCmd); ok {
		return x.SpecifyCmd
	}
	return nil
}

func (x *Command) GetConfigureCmd() *Configure_Command {
	if x, ok := x.GetCommand().(*Command_ConfigureCmd); ok {
		return x.ConfigureCmd
	}
	return nil
}

func (x *Command) GetOpenCmd() *Open_Command {
	if x, ok := x.GetCommand().(*Command_OpenCmd); ok {
		return x.OpenCmd
	}
	return nil
}

func (x *Command) GetProcessCmd() *Process_Command {
	if x, ok := x.GetCommand().(*Command_ProcessCmd); ok {
		return x.ProcessCmd
	}
	return nil
}

func (x *Command) GetTeardownCmd() *Teardown_Command {
	if x, ok := x.GetCommand().(*Command_TeardownCmd); ok {
		return x.TeardownCmd
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_SpecifyCmd struct {
	SpecifyCmd *Specify_Command `protobuf:"bytes,1,opt,name=specify_cmd,json=specifyCmd,proto3,oneof"`
}

type Command_ConfigureCmd struct {
	ConfigureCmd *Configure_Command `protobuf:"bytes,2,opt,name=configure_cmd,json=configureCmd,proto3,oneof"`
}

type Command_OpenCmd struct {
	OpenCmd *Open_Command `protobuf:"bytes,3,opt,name=open_cmd,json=openCmd,proto3,oneof"`
}

type Command_ProcessCmd struct {
	ProcessCmd *Process_Command `protobuf:"bytes,4,opt,name=process_cmd,json=processCmd,proto3,oneof"`
}

type Command_TeardownCmd struct {
	TeardownCmd *Teardown_Command `protobuf:"bytes,5,opt,name=teardown_cmd,json=teardownCmd,proto3,oneof"`
}

func (*Command_SpecifyCmd) isCommand_Command() {}

func (*Command_ConfigureCmd) isCommand_Command() {}

func (*Command_OpenCmd) isCommand_Command() {}

func (*Command_ProcessCmd) isCommand_Command() {}

func (*Command_TeardownCmd) isCommand_Command() {}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*CommandResponse_SpecifyResp
	//	*CommandResponse_ConfigureResp
	//	*CommandResponse_OpenResp
	//	*CommandResponse_ProcessResp
	//	*CommandResponse_TeardownResp
	Response isCommandResponse_Response `protobuf_oneof:"response"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{1}
}

func (m *CommandResponse) GetResponse() isCommandResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CommandResponse) GetSpecifyResp() *Specify_Response {
	if x, ok := x.GetResponse().(*CommandResponse_SpecifyResp); ok {
		return x.SpecifyResp
	}
	return nil
}

func (x *CommandResponse) GetConfigureResp() *Configure_Response {
	if x, ok := x.GetResponse().(*CommandResponse_ConfigureResp); ok {
		return x.ConfigureResp
	}
	return nil
}

func (x *CommandResponse) GetOpenResp() *Open_Response {
	if x, ok := x.GetResponse().(*CommandResponse_OpenResp); ok {
		return x.OpenResp
	}
	return nil
}

func (x *CommandResponse) GetProcessResp() *Process_Response {
	if x, ok := x.GetResponse().(*CommandResponse_ProcessResp); ok {
		return x.ProcessResp
	}
	return nil
}

func (x *CommandResponse) GetTeardownResp() *Teardown_Response {
	if x, ok := x.GetResponse().(*CommandResponse_TeardownResp); ok {
		return x.TeardownResp
	}
	return nil
}

type isCommandResponse_Response interface {
	isCommandResponse_Response()
}

type CommandResponse_SpecifyResp struct {
	SpecifyResp *Specify_Response `protobuf:"bytes,1,opt,name=specify_resp,json=specifyResp,proto3,oneof"`
}

type CommandResponse_ConfigureResp struct {
	ConfigureResp *Configure_Response `protobuf:"bytes,2,opt,name=configure_resp,json=configureResp,proto3,oneof"`
}

type CommandResponse_OpenResp struct {
	OpenResp *Open_Response `protobuf:"bytes,3,opt,name=open_resp,json=openResp,proto3,oneof"`
}

type CommandResponse_ProcessResp struct {
	ProcessResp *Process_Response `protobuf:"bytes,4,opt,name=process_resp,json=processResp,proto3,oneof"`
}

type CommandResponse_TeardownResp struct {
	TeardownResp *Teardown_Response `protobuf:"bytes,5,opt,name=teardown_resp,json=teardownResp,proto3,oneof"`
}

func (*CommandResponse_SpecifyResp) isCommandResponse_Response() {}

func (*CommandResponse_ConfigureResp) isCommandResponse_Response() {}

func (*CommandResponse_OpenResp) isCommandResponse_Response() {}

func (*CommandResponse_ProcessResp) isCommandResponse_Response() {}

func (*CommandResponse_TeardownResp) isCommandResponse_Response() {}

type Specify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specify) Reset() {
	*x = Specify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify) ProtoMessage() {}

func (x *Specify) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify.ProtoReflect.Descriptor instead.
func (*Specify) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2}
}

type Configure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Configure) Reset() {
	*x = Configure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure) ProtoMessage() {}

func (x *Configure) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure.ProtoReflect.Descriptor instead.
func (*Configure) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3}
}

type Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open) Reset() {
	*x = Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4}
}

type Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Process) Reset() {
	*x = Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5}
}

type Teardown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Teardown) Reset() {
	*x = Teardown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown) ProtoMessage() {}

func (x *Teardown) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown.ProtoReflect.Descriptor instead.
func (*Teardown) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6}
}

type Specify_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specify_Command) Reset() {
	*x = Specify_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Command) ProtoMessage() {}

func (x *Specify_Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Command.ProtoReflect.Descriptor instead.
func (*Specify_Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 0}
}

type Specify_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name is the name of the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Summary is a brief description of the plugin and what it does,
	// ideally not longer than one sentence.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Description is a longer form field, appropriate for README-like
	// text that the author can provide for documentation about the
	// usage of the plugin.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Version string. Should follow semantic versioning and use the "v"
	// prefix (e.g. v1.23.4).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Author declares the entity that created or maintains this plugin.
	Author string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	// A map that describes parameters available for configuring the
	// destination plugin.
	Parameters map[string]*Specify_Parameter `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err        string                        `protobuf:"bytes,7,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Specify_Response) Reset() {
	*x = Specify_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Response) ProtoMessage() {}

func (x *Specify_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Response.ProtoReflect.Descriptor instead.
func (*Specify_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Specify_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specify_Response) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Specify_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specify_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Specify_Response) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Specify_Response) GetParameters() map[string]*Specify_Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Specify_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Parameter describes a single config parameter.
type Specify_Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Default is the default value of the parameter. If there is no default
	// value use an empty string.
	Default string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	// Description explains what the parameter does and how to configure it.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Type defines the parameter data type.
	Type Specify_Parameter_Type `protobuf:"varint,3,opt,name=type,proto3,enum=processor.v1.Specify_Parameter_Type" json:"type,omitempty"`
	// Validations are validations to be made on the parameter.
	Validations []*Specify_Parameter_Validation `protobuf:"bytes,4,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (x *Specify_Parameter) Reset() {
	*x = Specify_Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Parameter) ProtoMessage() {}

func (x *Specify_Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Parameter.ProtoReflect.Descriptor instead.
func (*Specify_Parameter) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Specify_Parameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Specify_Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specify_Parameter) GetType() Specify_Parameter_Type {
	if x != nil {
		return x.Type
	}
	return Specify_Parameter_TYPE_UNSPECIFIED
}

func (x *Specify_Parameter) GetValidations() []*Specify_Parameter_Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

// Validation to be made on the parameter.
type Specify_Parameter_Validation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Specify_Parameter_Validation_Type `protobuf:"varint,1,opt,name=type,proto3,enum=processor.v1.Specify_Parameter_Validation_Type" json:"type,omitempty"`
	// The value to be compared with the parameter,
	// or a comma separated list in case of Validation.TYPE_INCLUSION or Validation.TYPE_EXCLUSION.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Specify_Parameter_Validation) Reset() {
	*x = Specify_Parameter_Validation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specify_Parameter_Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specify_Parameter_Validation) ProtoMessage() {}

func (x *Specify_Parameter_Validation) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specify_Parameter_Validation.ProtoReflect.Descriptor instead.
func (*Specify_Parameter_Validation) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{2, 2, 0}
}

func (x *Specify_Parameter_Validation) GetType() Specify_Parameter_Validation_Type {
	if x != nil {
		return x.Type
	}
	return Specify_Parameter_Validation_TYPE_UNSPECIFIED
}

func (x *Specify_Parameter_Validation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Configure_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Configure_Command) Reset() {
	*x = Configure_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure_Command) ProtoMessage() {}

func (x *Configure_Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure_Command.ProtoReflect.Descriptor instead.
func (*Configure_Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Configure_Command) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Configure_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Configure_Response) Reset() {
	*x = Configure_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configure_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure_Response) ProtoMessage() {}

func (x *Configure_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure_Response.ProtoReflect.Descriptor instead.
func (*Configure_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Configure_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Open_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Open_Command) Reset() {
	*x = Open_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open_Command) ProtoMessage() {}

func (x *Open_Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open_Command.ProtoReflect.Descriptor instead.
func (*Open_Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4, 0}
}

type Open_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Open_Response) Reset() {
	*x = Open_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Open_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open_Response) ProtoMessage() {}

func (x *Open_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open_Response.ProtoReflect.Descriptor instead.
func (*Open_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Open_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Process_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*v1.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Process_Command) Reset() {
	*x = Process_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Command) ProtoMessage() {}

func (x *Process_Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Command.ProtoReflect.Descriptor instead.
func (*Process_Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Process_Command) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Process_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Process_ProcessedRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Process_Response) Reset() {
	*x = Process_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_Response) ProtoMessage() {}

func (x *Process_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_Response.ProtoReflect.Descriptor instead.
func (*Process_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Process_Response) GetRecords() []*Process_ProcessedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type Process_ProcessedRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Record:
	//
	//	*Process_ProcessedRecord_SingleRecord
	//	*Process_ProcessedRecord_FilterRecord
	//	*Process_ProcessedRecord_ErrorRecord
	Record isProcess_ProcessedRecord_Record `protobuf_oneof:"record"`
}

func (x *Process_ProcessedRecord) Reset() {
	*x = Process_ProcessedRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_ProcessedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_ProcessedRecord) ProtoMessage() {}

func (x *Process_ProcessedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_ProcessedRecord.ProtoReflect.Descriptor instead.
func (*Process_ProcessedRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 2}
}

func (m *Process_ProcessedRecord) GetRecord() isProcess_ProcessedRecord_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *Process_ProcessedRecord) GetSingleRecord() *v1.Record {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_SingleRecord); ok {
		return x.SingleRecord
	}
	return nil
}

func (x *Process_ProcessedRecord) GetFilterRecord() *Process_FilterRecord {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_FilterRecord); ok {
		return x.FilterRecord
	}
	return nil
}

func (x *Process_ProcessedRecord) GetErrorRecord() *Process_ErrorRecord {
	if x, ok := x.GetRecord().(*Process_ProcessedRecord_ErrorRecord); ok {
		return x.ErrorRecord
	}
	return nil
}

type isProcess_ProcessedRecord_Record interface {
	isProcess_ProcessedRecord_Record()
}

type Process_ProcessedRecord_SingleRecord struct {
	SingleRecord *v1.Record `protobuf:"bytes,1,opt,name=single_record,json=singleRecord,proto3,oneof"`
}

type Process_ProcessedRecord_FilterRecord struct {
	FilterRecord *Process_FilterRecord `protobuf:"bytes,2,opt,name=filter_record,json=filterRecord,proto3,oneof"`
}

type Process_ProcessedRecord_ErrorRecord struct {
	ErrorRecord *Process_ErrorRecord `protobuf:"bytes,3,opt,name=error_record,json=errorRecord,proto3,oneof"`
}

func (*Process_ProcessedRecord_SingleRecord) isProcess_ProcessedRecord_Record() {}

func (*Process_ProcessedRecord_FilterRecord) isProcess_ProcessedRecord_Record() {}

func (*Process_ProcessedRecord_ErrorRecord) isProcess_ProcessedRecord_Record() {}

type Process_FilterRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Process_FilterRecord) Reset() {
	*x = Process_FilterRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_FilterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_FilterRecord) ProtoMessage() {}

func (x *Process_FilterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_FilterRecord.ProtoReflect.Descriptor instead.
func (*Process_FilterRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 3}
}

type Process_ErrorRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Process_ErrorRecord) Reset() {
	*x = Process_ErrorRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process_ErrorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process_ErrorRecord) ProtoMessage() {}

func (x *Process_ErrorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process_ErrorRecord.ProtoReflect.Descriptor instead.
func (*Process_ErrorRecord) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{5, 4}
}

func (x *Process_ErrorRecord) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Teardown_Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Teardown_Command) Reset() {
	*x = Teardown_Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown_Command) ProtoMessage() {}

func (x *Teardown_Command) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown_Command.ProtoReflect.Descriptor instead.
func (*Teardown_Command) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6, 0}
}

type Teardown_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Teardown_Response) Reset() {
	*x = Teardown_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_v1_processor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teardown_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teardown_Response) ProtoMessage() {}

func (x *Teardown_Response) ProtoReflect() protoreflect.Message {
	mi := &file_processor_v1_processor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teardown_Response.ProtoReflect.Descriptor instead.
func (*Teardown_Response) Descriptor() ([]byte, []int) {
	return file_processor_v1_processor_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Teardown_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_processor_v1_processor_proto protoreflect.FileDescriptor

var file_processor_v1_processor_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x64, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x40, 0x0a, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x79, 0x43, 0x6d, 0x64, 0x12, 0x46, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x37, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x70,
	0x65, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x40, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x63, 0x6d, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6d, 0x64, 0x12, 0x43, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x72, 0x64,
	0x6f, 0x77, 0x6e, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x61,
	0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x0b, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x43, 0x6d, 0x64, 0x42, 0x09, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xf6, 0x02, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x49, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x6f,
	0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0d,
	0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xb4, 0x07, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x1a, 0x09, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0xce, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x5e, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xcc, 0x04, 0x0a, 0x09, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x0b,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0xfc, 0x01, 0x0a, 0x0a, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10,
	0x03, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x43, 0x4c, 0x55, 0x53,
	0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x58,
	0x43, 0x4c, 0x55, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x45, 0x47, 0x45, 0x58, 0x10, 0x06, 0x22, 0x7c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46,
	0x4c, 0x4f, 0x41, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42,
	0x4f, 0x4f, 0x4c, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49,
	0x4c, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x55, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x22, 0xc5, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x99, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x4f, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x2f, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x1a, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x22, 0xac, 0x03, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x37, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x1a, 0xe9, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x39, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x49, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0c,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x46, 0x0a, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0e,
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x1f,
	0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x33, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x42, 0xc7, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x52, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x69,
	0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_processor_v1_processor_proto_rawDescOnce sync.Once
	file_processor_v1_processor_proto_rawDescData = file_processor_v1_processor_proto_rawDesc
)

func file_processor_v1_processor_proto_rawDescGZIP() []byte {
	file_processor_v1_processor_proto_rawDescOnce.Do(func() {
		file_processor_v1_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_processor_v1_processor_proto_rawDescData)
	})
	return file_processor_v1_processor_proto_rawDescData
}

var file_processor_v1_processor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_processor_v1_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_processor_v1_processor_proto_goTypes = []interface{}{
	(Specify_Parameter_Type)(0),            // 0: processor.v1.Specify.Parameter.Type
	(Specify_Parameter_Validation_Type)(0), // 1: processor.v1.Specify.Parameter.Validation.Type
	(*Command)(nil),                        // 2: processor.v1.Command
	(*CommandResponse)(nil),                // 3: processor.v1.CommandResponse
	(*Specify)(nil),                        // 4: processor.v1.Specify
	(*Configure)(nil),                      // 5: processor.v1.Configure
	(*Open)(nil),                           // 6: processor.v1.Open
	(*Process)(nil),                        // 7: processor.v1.Process
	(*Teardown)(nil),                       // 8: processor.v1.Teardown
	(*Specify_Command)(nil),                // 9: processor.v1.Specify.Command
	(*Specify_Response)(nil),               // 10: processor.v1.Specify.Response
	(*Specify_Parameter)(nil),              // 11: processor.v1.Specify.Parameter
	nil,                                    // 12: processor.v1.Specify.Response.ParametersEntry
	(*Specify_Parameter_Validation)(nil),   // 13: processor.v1.Specify.Parameter.Validation
	(*Configure_Command)(nil),              // 14: processor.v1.Configure.Command
	(*Configure_Response)(nil),             // 15: processor.v1.Configure.Response
	nil,                                    // 16: processor.v1.Configure.Command.ParametersEntry
	(*Open_Command)(nil),                   // 17: processor.v1.Open.Command
	(*Open_Response)(nil),                  // 18: processor.v1.Open.Response
	(*Process_Command)(nil),                // 19: processor.v1.Process.Command
	(*Process_Response)(nil),               // 20: processor.v1.Process.Response
	(*Process_ProcessedRecord)(nil),        // 21: processor.v1.Process.ProcessedRecord
	(*Process_FilterRecord)(nil),           // 22: processor.v1.Process.FilterRecord
	(*Process_ErrorRecord)(nil),            // 23: processor.v1.Process.ErrorRecord
	(*Teardown_Command)(nil),               // 24: processor.v1.Teardown.Command
	(*Teardown_Response)(nil),              // 25: processor.v1.Teardown.Response
	(*v1.Record)(nil),                      // 26: opencdc.v1.Record
}
var file_processor_v1_processor_proto_depIdxs = []int32{
	9,  // 0: processor.v1.Command.specify_cmd:type_name -> processor.v1.Specify.Command
	14, // 1: processor.v1.Command.configure_cmd:type_name -> processor.v1.Configure.Command
	17, // 2: processor.v1.Command.open_cmd:type_name -> processor.v1.Open.Command
	19, // 3: processor.v1.Command.process_cmd:type_name -> processor.v1.Process.Command
	24, // 4: processor.v1.Command.teardown_cmd:type_name -> processor.v1.Teardown.Command
	10, // 5: processor.v1.CommandResponse.specify_resp:type_name -> processor.v1.Specify.Response
	15, // 6: processor.v1.CommandResponse.configure_resp:type_name -> processor.v1.Configure.Response
	18, // 7: processor.v1.CommandResponse.open_resp:type_name -> processor.v1.Open.Response
	20, // 8: processor.v1.CommandResponse.process_resp:type_name -> processor.v1.Process.Response
	25, // 9: processor.v1.CommandResponse.teardown_resp:type_name -> processor.v1.Teardown.Response
	12, // 10: processor.v1.Specify.Response.parameters:type_name -> processor.v1.Specify.Response.ParametersEntry
	0,  // 11: processor.v1.Specify.Parameter.type:type_name -> processor.v1.Specify.Parameter.Type
	13, // 12: processor.v1.Specify.Parameter.validations:type_name -> processor.v1.Specify.Parameter.Validation
	11, // 13: processor.v1.Specify.Response.ParametersEntry.value:type_name -> processor.v1.Specify.Parameter
	1,  // 14: processor.v1.Specify.Parameter.Validation.type:type_name -> processor.v1.Specify.Parameter.Validation.Type
	16, // 15: processor.v1.Configure.Command.parameters:type_name -> processor.v1.Configure.Command.ParametersEntry
	26, // 16: processor.v1.Process.Command.records:type_name -> opencdc.v1.Record
	21, // 17: processor.v1.Process.Response.records:type_name -> processor.v1.Process.ProcessedRecord
	26, // 18: processor.v1.Process.ProcessedRecord.single_record:type_name -> opencdc.v1.Record
	22, // 19: processor.v1.Process.ProcessedRecord.filter_record:type_name -> processor.v1.Process.FilterRecord
	23, // 20: processor.v1.Process.ProcessedRecord.error_record:type_name -> processor.v1.Process.ErrorRecord
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_processor_v1_processor_proto_init() }
func file_processor_v1_processor_proto_init() {
	if File_processor_v1_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_processor_v1_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specify_Parameter_Validation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configure_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Open_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_ProcessedRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_FilterRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process_ErrorRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown_Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_v1_processor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teardown_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_processor_v1_processor_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Command_SpecifyCmd)(nil),
		(*Command_ConfigureCmd)(nil),
		(*Command_OpenCmd)(nil),
		(*Command_ProcessCmd)(nil),
		(*Command_TeardownCmd)(nil),
	}
	file_processor_v1_processor_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandResponse_SpecifyResp)(nil),
		(*CommandResponse_ConfigureResp)(nil),
		(*CommandResponse_OpenResp)(nil),
		(*CommandResponse_ProcessResp)(nil),
		(*CommandResponse_TeardownResp)(nil),
	}
	file_processor_v1_processor_proto_msgTypes[19].OneofWrappers = []interface{}{
		(*Process_ProcessedRecord_SingleRecord)(nil),
		(*Process_ProcessedRecord_FilterRecord)(nil),
		(*Process_ProcessedRecord_ErrorRecord)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processor_v1_processor_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_processor_v1_processor_proto_goTypes,
		DependencyIndexes: file_processor_v1_processor_proto_depIdxs,
		EnumInfos:         file_processor_v1_processor_proto_enumTypes,
		MessageInfos:      file_processor_v1_processor_proto_msgTypes,
	}.Build()
	File_processor_v1_processor_proto = out.File
	file_processor_v1_processor_proto_rawDesc = nil
	file_processor_v1_processor_proto_goTypes = nil
	file_processor_v1_processor_proto_depIdxs = nil
}
